version: "3.9"

services:
  apriltag_detector:
    build: .
    container_name: apriltag_detector
    network_mode: host
    ipc: host
    volumes:
      - ./ros_ws/src:/ros_ws/src
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    restart: "no"
