version: "3.9"

services:
  ir_cam_ros:
    build: .
    container_name: ir_cam_ros
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    restart: "no"