apriltag_field:
  ros__parameters:
    image_transport: raw
    family: "16h5"
    size: 0.01
    max_hamming: 0
    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    pose_estimation_method: "pnp"
