version: "3.9"

services:
  rviz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rviz2_viewer
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./ros_ws/src:/ros_ws/src   
    command: ros2 run rviz2 rviz2 -d /ros_ws/multirobot_rviz.rviz
    restart: "no"

