image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [628.36227,   0.     , 329.79835,
           0.     , 625.51676, 227.0305 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.226974, -0.429325, 0.001027, 0.010438, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [645.7981 ,   0.     , 334.3313 ,   0.     ,
           0.     , 647.52539, 226.90843,   0.     ,
           0.     ,   0.     ,   1.     ,   0.   ] 
